{{- if or .Values.secrets.judgeApiKey -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mithril.fullname" . }}-secrets
  labels:
    {{- include "mithril.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.secrets.judgeApiKey }}
  MITHRIL_JUDGE_API_KEY: {{ .Values.secrets.judgeApiKey | quote }}
  {{- end }}
{{- end }}
